/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    homepage: Homepage;
    blocks: Block;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Posts collection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  title: string;
  ingress?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        tags: 'technology' | 'science' | 'art' | 'culture' | 'sports';
        id?: string | null;
      }[]
    | null;
  group?: {
    heroBlocks?:
      | (
          | {
              title?: string | null;
              image?: (string | null) | Media;
              content?: string | null;
              'image position'?: ('Left' | 'Right') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'defaultHero';
            }
          | {
              role?: string | null;
              name?: string | null;
              description?: string | null;
              image?: (string | null) | Media;
              group?: {
                bornIn?: string | null;
                experience?: string | null;
                bornDate?: string | null;
                socialLinks?:
                  | {
                      link: {
                        type?: ('reference' | 'custom') | null;
                        newTab?: boolean | null;
                        reference?:
                          | ({
                              relationTo: 'pages';
                              value: string | Page;
                            } | null)
                          | ({
                              relationTo: 'posts';
                              value: string | Post;
                            } | null);
                        url?: string | null;
                        label: string;
                      };
                      id?: string | null;
                    }[]
                  | null;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'personalHero';
            }
        )[]
      | null;
    /**
     * Här väljer du vilka content block du vill använda på denna post.
     */
    contentBlocks?: {
      blocks?:
        | (
            | Accordion
            | InfoBlock
            | {
                title?: string | null;
                description?: string | null;
                imageArray?:
                  | {
                      image?: (string | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'contentWithMedia';
              }
            | {
                title?: string | null;
                description?: string | null;
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                image?: (string | null) | Media;
                imagePosition?: ('left' | 'right') | null;
                backgroundColor?: ('bg-red-400' | 'bg-blue-400' | 'bg-green-400') | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'leftRight';
              }
          )[]
        | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Pages collection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Accordion".
 */
export interface Accordion {
  items?:
    | {
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  image?: (string | null) | Media;
  imagePosition?: ('Left' | 'Right') | null;
  /**
   * Om du kryssar för denna, så kan bara en accordion vara öppen samtidigt. Så öppnar man en och sedan en ny så kommer den första att stängas.
   */
  openAtOnce?: ('One' | 'Multiple') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Info Block".
 */
export interface InfoBlock {
  title?: string | null;
  description?: string | null;
  innerContent?:
    | {
        innerHeading?: string | null;
        innerDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  title?: T;
  ingress?: T;
  tags?:
    | T
    | {
        tags?: T;
        id?: T;
      };
  group?:
    | T
    | {
        heroBlocks?:
          | T
          | {
              defaultHero?:
                | T
                | {
                    title?: T;
                    image?: T;
                    content?: T;
                    'image position'?: T;
                    id?: T;
                    blockName?: T;
                  };
              personalHero?:
                | T
                | {
                    role?: T;
                    name?: T;
                    description?: T;
                    image?: T;
                    group?:
                      | T
                      | {
                          bornIn?: T;
                          experience?: T;
                          bornDate?: T;
                          socialLinks?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        contentBlocks?:
          | T
          | {
              blocks?:
                | T
                | {
                    accordion?: T | AccordionSelect<T>;
                    infoBlock?: T | InfoBlockSelect<T>;
                    contentWithMedia?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          imageArray?:
                            | T
                            | {
                                image?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    leftRight?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                              };
                          image?: T;
                          imagePosition?: T;
                          backgroundColor?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Accordion_select".
 */
export interface AccordionSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  image?: T;
  imagePosition?: T;
  openAtOnce?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Info Block_select".
 */
export interface InfoBlockSelect {
  title?: boolean;
  description?: boolean;
  innerContent?:
    | boolean
    | {
        innerHeading?: boolean;
        innerDescription?: boolean;
        id?: boolean;
      };
  image?: boolean;
  id?: boolean;
  blockName?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  logo?: (string | null) | Media;
  displayAs?: ('hamburger' | 'normal') | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  leftColumn?: {
    logo?: (string | null) | Media;
    title?: string | null;
    content?: string | null;
  };
  middleColumn?: {
    title?: string | null;
    navItemsMiddleCol?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  rightColumn?: {
    title?: string | null;
    navItemsRightCol?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  title: string;
  group?: {
    heroBlocks?:
      | (
          | {
              title?: string | null;
              image?: (string | null) | Media;
              content?: string | null;
              'image position'?: ('Left' | 'Right') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'defaultHero';
            }
          | {
              role?: string | null;
              name?: string | null;
              description?: string | null;
              image?: (string | null) | Media;
              group?: {
                bornIn?: string | null;
                experience?: string | null;
                bornDate?: string | null;
                socialLinks?:
                  | {
                      link: {
                        type?: ('reference' | 'custom') | null;
                        newTab?: boolean | null;
                        reference?:
                          | ({
                              relationTo: 'pages';
                              value: string | Page;
                            } | null)
                          | ({
                              relationTo: 'posts';
                              value: string | Post;
                            } | null);
                        url?: string | null;
                        label: string;
                      };
                      id?: string | null;
                    }[]
                  | null;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'personalHero';
            }
        )[]
      | null;
    /**
     * Här väljer du vilka content block du vill använda på denna post.
     */
    contentBlocks?: {
      blocks?: (Accordion | InfoBlock)[] | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * En samlingssida där alla block är tillgängliga och används för att visa blocken på en samlings sida.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: string;
  title?: string | null;
  group?: {
    heroBlocks?:
      | (
          | {
              title?: string | null;
              image?: (string | null) | Media;
              content?: string | null;
              'image position'?: ('Left' | 'Right') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'defaultHero';
            }
          | {
              role?: string | null;
              name?: string | null;
              description?: string | null;
              image?: (string | null) | Media;
              group?: {
                bornIn?: string | null;
                experience?: string | null;
                bornDate?: string | null;
                socialLinks?:
                  | {
                      link: {
                        type?: ('reference' | 'custom') | null;
                        newTab?: boolean | null;
                        reference?:
                          | ({
                              relationTo: 'pages';
                              value: string | Page;
                            } | null)
                          | ({
                              relationTo: 'posts';
                              value: string | Post;
                            } | null);
                        url?: string | null;
                        label: string;
                      };
                      id?: string | null;
                    }[]
                  | null;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'personalHero';
            }
        )[]
      | null;
    /**
     * Här väljer du vilka content block du vill använda på denna post.
     */
    contentBlocks?: {
      blocks?:
        | (
            | Accordion
            | InfoBlock
            | {
                title?: string | null;
                description?: string | null;
                imageArray?:
                  | {
                      image?: (string | null) | Media;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'contentWithMedia';
              }
            | {
                title?: string | null;
                description?: string | null;
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                image?: (string | null) | Media;
                imagePosition?: ('left' | 'right') | null;
                backgroundColor?: ('bg-red-400' | 'bg-blue-400' | 'bg-green-400') | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'leftRight';
              }
          )[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  displayAs?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  leftColumn?:
    | T
    | {
        logo?: T;
        title?: T;
        content?: T;
      };
  middleColumn?:
    | T
    | {
        title?: T;
        navItemsMiddleCol?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  rightColumn?:
    | T
    | {
        title?: T;
        navItemsRightCol?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  title?: T;
  group?:
    | T
    | {
        heroBlocks?:
          | T
          | {
              defaultHero?:
                | T
                | {
                    title?: T;
                    image?: T;
                    content?: T;
                    'image position'?: T;
                    id?: T;
                    blockName?: T;
                  };
              personalHero?:
                | T
                | {
                    role?: T;
                    name?: T;
                    description?: T;
                    image?: T;
                    group?:
                      | T
                      | {
                          bornIn?: T;
                          experience?: T;
                          bornDate?: T;
                          socialLinks?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        contentBlocks?:
          | T
          | {
              blocks?:
                | T
                | {
                    accordion?: T | AccordionSelect<T>;
                    infoBlock?: T | InfoBlockSelect<T>;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  title?: T;
  group?:
    | T
    | {
        heroBlocks?:
          | T
          | {
              defaultHero?:
                | T
                | {
                    title?: T;
                    image?: T;
                    content?: T;
                    'image position'?: T;
                    id?: T;
                    blockName?: T;
                  };
              personalHero?:
                | T
                | {
                    role?: T;
                    name?: T;
                    description?: T;
                    image?: T;
                    group?:
                      | T
                      | {
                          bornIn?: T;
                          experience?: T;
                          bornDate?: T;
                          socialLinks?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        contentBlocks?:
          | T
          | {
              blocks?:
                | T
                | {
                    accordion?: T | AccordionSelect<T>;
                    infoBlock?: T | InfoBlockSelect<T>;
                    contentWithMedia?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          imageArray?:
                            | T
                            | {
                                image?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    leftRight?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                              };
                          image?: T;
                          imagePosition?: T;
                          backgroundColor?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}